# Generated by Django 4.0.6 on 2023-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=50)),
                ('proddesc', models.CharField(max_length=50)),
                ('prodprice', models.DecimalField(decimal_places=0, max_digits=3)),
                ('prodsize', models.DecimalField(decimal_places=0, max_digits=3)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
            ],
        ),
    ]
