# Generated by Django 4.0.6 on 2023-05-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_desc_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
