# Generated by Django 4.0.6 on 2023-05-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_product_image_remove_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='prodname',
        ),
    ]
