# Generated by Django 4.0.6 on 2023-05-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_name_product_prodname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodname',
            new_name='name',
        ),
    ]
