# Generated by Django 4.0.6 on 2023-05-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_prodname_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='prodname',
        ),
    ]
